run-name: "Build pytorch:2.0-r35.2"
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'placeholder'
jobs:
  pytorch_2.0-r35.2:
    runs-on: self-hosted-jetson r35.2
    steps:
    - run: echo "Building pytorch:2.0-r35.2"
