name: "pytorch_20-r327"
run-name: "Build pytorch_20-r327"
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'dev'
jobs:
  pytorch_20-r327:
    runs-on: [self-hosted-jetson, r327]
    steps:
    - run: echo "Building pytorch_20-r327"
