name: "pytorch_20-r327"
run-name: "Build pytorch_20-r327"
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'dev'
    paths:
      - '.github/workflows/pytorch_20-r327.yml'
jobs:
  pytorch_20-r327:
    runs-on: [self-hosted-jetson, r32.7]
    steps:
    - run: echo "Building pytorch_20-r327"
