name: "xformers_jp51"
run-name: "Build xformers (JetPack 5.1)"
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'dev'
    paths:
      - '.github/workflows/xformers_jp51.yml'
      - 'packages/llm/xformers/*'
      - '!packages/llm/xformers/README.md'
      - 'packages/build-essential/*'
      - '!packages/build-essential/README.md'
      - 'packages/python/*'
      - '!packages/python/README.md'
      - 'packages/numpy/*'
      - '!packages/numpy/README.md'
      - 'packages/cmake/cmake_pip/*'
      - '!packages/cmake/cmake_pip/README.md'
      - 'packages/onnx/*'
      - '!packages/onnx/README.md'
      - 'packages/pytorch/*'
      - '!packages/pytorch/README.md'
jobs:
  xformers_jp51:
    runs-on: [self-hosted, jetson, jp51]
    steps:
      - run: |
         cat /etc/nv_tegra_release 
      - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
        run: |
         echo "$RUNNER_WORKSPACE" 
         cd $RUNNER_WORKSPACE 
         git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
         cd jetson-containers 
         git fetch origin 
         git checkout $GITHUB_SHA 
         git status 
         ls -a 
      - run: ./build.sh --name=runner/ --push=dustynv xformers